sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
  # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine

install:
  - sudo pip install docker-py
  
  # Install ansible
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python

  # force use of /usr/bin/python
  - PATH="/usr/bin:$PATH" 
  
  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path and host_key_checking turned off
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False\n' >ansible.cfg

script:
  # which python are we using
  - wheris python
  - python --version

  # Install requirements
  - ansible-galaxy install chrismeyersfsu.provision_docker

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

# notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
