sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
  # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path and host_key_checking turned off
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False\n' >ansible.cfg

script:
  # Install requirements
  - ansible-galaxy install chrismeyersfsu.provision_docker

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

# notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
